// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THMY_API.Models.DBContext;

#nullable disable

namespace THMY_API.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20251106082949_updateCreateAt")]
    partial class updateCreateAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("THMY_API.Models.APIStorage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("apiSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("applicationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("APIStroageKey");
                });

            modelBuilder.Entity("THMY_API.Models.EmpRole", b =>
                {
                    b.Property<string>("empId")
                        .HasColumnType("TEXT");

                    b.Property<int>("roleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("systemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("empId", "roleId", "systemId");

                    b.ToTable("EmpRole");
                });

            modelBuilder.Entity("THMY_API.Models.Permission", b =>
                {
                    b.Property<int>("permissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("permissionDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("permissionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("systemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("permissionId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("THMY_API.Models.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("roleDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("roleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("THMY_API.Models.RolePermission", b =>
                {
                    b.Property<int>("roleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("permissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("systemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("roleId", "permissionId", "systemId");

                    b.ToTable("RolePermission");
                });
#pragma warning restore 612, 618
        }
    }
}
